SELECT
  COUNT(*) AS rows,
  COUNT(DISTINCT DTE_EVENT) AS days_loaded,
  COUNT(DISTINCT NAM_COUNTRY) AS countries,
  COUNT(DISTINCT NAM_CITY) AS cities
FROM `new-risk-monitor.BSG_DS_NMR.T_DW_BSG_GDELT_RISK_EVENTS`;
