SELECT
  DTE_EVENT,
  NAM_COUNTRY,
  NAM_CITY,
  CNT_EVENTS,
  NUM_RISK_SCORE
FROM `new-risk-monitor.BSG_DS_NMR.T_DW_BSG_GDELT_RISK_EVENTS`
WHERE NUM_RISK_SCORE >= 60
ORDER BY NUM_RISK_SCORE DESC
LIMIT 25;
