SELECT
  DTE_EVENT,
  AVG(NUM_RISK_SCORE) AS avg_risk_score,
  MAX(NUM_RISK_SCORE) AS max_risk_score
FROM `new-risk-monitor.BSG_DS_NMR.T_DW_BSG_GDELT_RISK_EVENTS`
GROUP BY DTE_EVENT
ORDER BY DTE_EVENT;
